### ISSUE TITLE
Add support for matchValue to match arrays on a custom field

### ISSUE THREAD

**Issue by timkelty** [barrelstrength/craft-sprout-import#39]
The docs show `related.[fieldHandle].matchValue` being able to be an array: https://sprout.barrelstrengthdesign.com/craft-plugins/import/docs/importing-data/create-elements-on-the-fly#example-using-the-createifnotfound-and-newelements-keys

However, if it is an array, an error is thrown.

The problem exists [here](https://github.com/barrelstrength/craft-sprout-import/blob/f01563c4914e5fd25722bbde3b68396245dcb568/src/services/ElementImporter.php#L243), where you're using `$matchValue` as a scalar value, not accounting for it being an array.

Example import json:

```
[
  {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\Entry",
    "attributes": {
      "sectionId": 4,
      "siteId": 2,
      "typeId": 4,
      "enabled": true,
      "authorId": 34
    },
    "content": {
      "title": "Sofa By-the-Inch",
      "fields": {
        "legacyId": 6,
        "patternNumber": "1288"
      },
      "related": {
        "materials": {
          "@model": "barrelstrength\\sproutimport\\importers\\elements\\Entry",
          "matchBy": "legacyId",
          "matchValue": [1, 2],
          "createIfNotFound": true,
          "newElements": [
            {
              "@model": "barrelstrength\\sproutimport\\importers\\elements\\Entry",
              "attributes": {
                "sectionId": 8,
                "enabled": true
              },
              "content": {
                "title": "Americana Satin",
                "fields": {
                  "legacyId": 1
                }
              }
            },
            {
              "@model": "barrelstrength\\sproutimport\\importers\\elements\\Entry",
              "attributes": {
                "sectionId": 8,
                "enabled": true
              },
              "content": {
                "title": "Preservation Aged",
                "fields": {
                  "legacyId": 2
                }
              }
            }
          ]
        }
      }
    },
    "settings": {
      "updateElement": {
        "matchBy": "legacyId",
        "matchValue": 6,
        "matchCriteria": {
          "sectionId": 4,
          "siteId": 2
        }
      }
    }
  }
]
```

Stack trace:
```
2018-05-21 11:38:16 [-][-][-][error][sprout-import] Unable to run Sprout Import job.
2018-05-21 11:38:16 [-][-][-][error][sprout-import] Array to string conversion
2018-05-21 11:38:16 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [19] Importing Data. (attempt: 1) - Error (time: 1.673s): Array to string conversion
2018-05-21 11:38:16 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /app/vendor/composer/barrelstrength/sprout-import/src/services/ElementImporter.php:243
Stack trace:
#0 /app/vendor/composer/barrelstrength/sprout-base/src/app/import/base/ElementImporter.php(146): barrelstrength\sproutimport\services\ElementImporter->resolveRelationships()
#1 /app/vendor/composer/barrelstrength/sprout-base/src/app/import/base/Importer.php(93): barrelstrength\sproutimport\importers\elements\Entry->setModel()
#2 /app/vendor/composer/barrelstrength/sprout-base/src/app/import/services/Importers.php(263): barrelstrength\sproutimport\importers\elements\Entry->__construct()
#3 /app/vendor/composer/barrelstrength/sprout-base/src/app/import/services/Importers.php(295): barrelstrength\sproutbase\app\import\services\Importers->getImporter()
#4 /app/vendor/composer/barrelstrength/sprout-import/src/queue/jobs/Import.php(43): barrelstrength\sproutbase\app\import\services\Importers->save()
```

**Comment by BenParizek** [comment]
@timkelty This is expected behavior at the moment. I've updated this to be a feature request.

We do support matching arrays on default properties of an element. The example you referenced uses the `slug` property. You could also use an array to match `id` or any other default properties on an Element. [See here](https://github.com/barrelstrength/craft-sprout-import/blob/v1/src/services/ElementImporter.php#L260)

In your case, `legacyId` is a custom field, and attempting to match an array of options on a custom field uses the Element `search` method and the costs of trying to match an array get more expensive. [See here](https://github.com/barrelstrength/craft-sprout-import/blob/v1/src/services/ElementImporter.php#L243)

My best recommendation at the moment, if you have to match an array is to try to do it on one of the default properties of the Element you are importing. If that's not possible, you may have to import your data in one pass and generate a second import file from the imported data to build an updated import to match a known ID or something like that.

**Comment by timkelty** [comment]
Gotcha, thanks.

If it doesn't end up getting tackled soon, maybe it would be a good idea to throw an exception if the `matchValue` isn't a default prop.

**Comment by BenParizek** [comment]
@timkelty Noting this here too.

This has been updated in the latest release. We've done away with the matchBy, matchValue, and matchCriteria syntax in favor of a new params syntax which gives you control to do whatever you would like. All Craft 3 examples have been updated in the docs to use params.
